### ISSUE TITLE
ket and  `part: fell of the end` error

### ISSUE THREAD

**Issue by barton-willis** [QMeqGR/qm-maxima#1]
Are you certain that the logic in the function `ket`  that declares some symbols complex is really needed?  Maxima's conjugate code examines if a symbol has been declared complex, but  not much else in Maxima does.  One reason I ask, is that the `ket` code sometimes gives an error that could be difficult for a user to understand:

OK:
~~~
(%i6) ket(1,2);
(%o6) matrix([1],[2])
~~~
Likely not what you want:
~~~
(%i7) ket([1,2]);
part: fell off the end.
~~~

As an alternative, might it work to use `listofvars` to declare all of them except for `%pi, %e, ...` to be complex?

**Comment by QMeqGR** [comment]
I removed the code that 'declare's variables complex. Robert made some suggestions that will likely change the way kets and bras are defined, so this remaining issue may go away soon.

**Comment by QMeqGR** [comment]
This code now leaves expressions like ket(a,b) alone, and for elements entered as a list like, ket([a,b]) returns a matrix representation.
