### ISSUE TITLE
ketp called on a non-matrix throws a error

### ISSUE THREAD

**Issue by barton-willis** [QMeqGR/qm-maxima#2]
Calling `ketp` on a not matrix throws an error. This is OK, but would it be more useful to return `false` for this case?

~~~
(%i5)	ketp(a+b);
The first argument of the function matrix_size must be a matrix
~~~

Possible replacement--this version rejects matrix entries that are matrices, lists, or sets:
~~~
  myketp(psi) := block([r,c],
     if matrixp(psi) then (
        [r,c] : matrix_size(psi),
        (c = 1) and (r > 1) and every(lambda([q], not (matrixp(q) or listp(q) or setp(q))), psi))
    else false);
~~~

**Comment by QMeqGR** [comment]
Thank you, I have updated the code.
