### ISSUE TITLE
Implementation of tpket/tpbra as lists and failed test cases due to tpket expressions getting resimplified

### ISSUE THREAD

**Issue by robert-dodier** [QMeqGR/qm-maxima#6]
I'm seeing some test cases involving `tpket` being reported as failures, although the expected and actual results appear to be the same. Here's the first one, as shown in `rtest_qm.ERR` after running `batch("rtest_qm.mac", test)`:

```
/* Problem 95 (line 301) */
K:Jtsqr(k),K = [tpket,2*ħ^2,ket([1,1]),ket([1,-1])]+[tpket,2*ħ^2,ket([1,0]),ket([1,0])],k = [tpket,1,ket([1,1]),ket([1,-1])];
/* Erroneous Result?:
[tpket,2*ħ^2,ket([1,1]),ket([1,-1])]+[tpket,2*ħ^2,ket([1,0]),ket([1,0])] */ 
/* Expected result: */
[tpket,2*ħ^2,ket([1,1]),ket([1,-1])]+[tpket,2*ħ^2,ket([1,0]),ket([1,0])];
```

Tracing through the functions in `src/mload.lisp` in the Maxima source code shows that the test failure is coming from SIMPLE-EQUAL-P, which is calling a function APPROX-ALIKE to compare the actual to the expected **after** resimplifying both expressions.

Now the actual result is coming out of a function (`Jtsqr` and others) which has `listarith: false` temporarily, to suppress lists being added element by element. However, the expected result, having been read out of the test script, is not known to be simplified (as marked by the SIMP flag in its expression car), so it gets resimplified with the prevailing value of `listarith` in force, namely `true`, and elements are added element by element. Now the two expressions are compared and they are different, so the test fails.

The resimplification of actual and expected results is necessary to ensure that expected results are in the same internal form as actual results, with arithmetic operators being the chief concerns. I can see that it might be argued that the test comparator shouldn't always resimplify, although at this point I am inclined to reserve judgement on that point.

I think the bigger issue for qm-maxima is the implementation of `tpket` and `tpbra` as lists. I think this is problematic, for the reason seen here, that it makes those expressions susceptible to general list operations, which aren't always applicable. Also, it is can be expressed more clearly by making `tpket` or `tpbra` the operator.

So at this point my advice is to reimplement `tpket` and `tpbra` as expressions in which `tpket` or `tpbra` is the operator, with the arguments as they are in the lists at present.

I see that there are some expressions in which `tpket` or `tpbra` has 2 arguments and some where it has 3. That's A-OK from Maxima's point of view -- there is no requirement that operators always have the same number of arguments. E.g. the first rule in `tprod.mac` could just as well be `tellsimp (tpket (k1, k2), tpket (1, k1, k2))`.

**Comment by QMeqGR** [comment]
Robert: Thanks so much for the detailed analysis. I followed your suggestion and reimplemented the tpket and tpbra expressions. Now rtest_qm.mac passes all tests without error. -Eric
